Gp3 throughput support
cloudfoundry/bosh-aws-cpi-release pull request #126
Opened 2022-01-31 13:52 UTC by schmidtsv

Adding support for both iops and throughput values of GP3 disks. 

- Added tests that test iops and throughput in the same fashion as io1s iops are tested
- Works on root, ephemeral and persistent disks.
- Note: values below the base of 3000 iops and 125mbps that are specified will be bumped by amazon to the baseline. 
- Test suite for block_device_manager are green. Due to me not having a playground AWS account I have not ran the full suite (as I did not touch most of the CPI)
- Manual integration test on AWS done.

2022-01-31 14:46 UTC, lnguyen commented
Can you squash commit down @schmidtsv ?

2022-01-31 15:28 UTC, schmidtsv commented
> Can you squash commit down @schmidtsv ?

I squashed it down

2022-01-31 18:50 UTC, lnguyen approved these changes
LGTM

2022-02-02 10:57 UTC, rkoster requested changes
Just some small suggestions, but looks good overal.

2022-02-02 10:57 UTC, rkoster commented on src/bosh_aws_cpi/lib/cloud/aws/volume_properties.rb
> +        end
```suggestion
        #On GP3 you can leave those values empty and get 3000 iops/125mb/s throughput
        if %w(io1 gp3).include?(@type) && @iops.to_i.nonzero?
          root_device[:iops] = @iops
        end
```

2022-02-02 10:57 UTC, rkoster commented on src/bosh_aws_cpi/lib/cloud/aws/volume_properties.rb
> +        end
```suggestion
        if @type == 'gp3' && @throughput.to_i.nonzero?
          root_device[:throughput] = @throughput
        end
```

2022-02-02 12:18 UTC, rkoster approved these changes

2022-02-02 12:18 UTC, rkoster commented
Thanks! @schmidtsv

2022-02-02 12:18 UTC, merged