Use the dualstack support of the aws-sdk to support IPv6
cloudfoundry/bosh-aws-cpi-release pull request #163
Opened 2024-07-17 15:05 UTC by max-soe

AWS not support IPv6 with the normal endpoints. They introduced new endpoints: https://docs.aws.amazon.com/ec2/latest/devguide/ec2-endpoints.html

Luckily the AWS-RUBY-SDK already support this endpoint. It's only necessary to set the use_dualstack_endpoint parameter. As this support ipv4 and ipv6, i think we can use this as default.

2024-07-18 14:43 UTC, beyhan commented
@max-soe Could you please check whether the dualstack is available on GOV cloud? Maybe we can make it opt-in as discussed during the FI WG call.

2024-07-18 14:44 UTC, beyhan requested changes
Please check my previous comment.

2024-07-25 21:04 UTC, ystros approved these changes
Looks fine overall. The AWS docs indicate that the normal US gov regions support the dualstack endpoints. It's unclear whether the secret US gov cloud system supports them because the docs don't seem to be public.

2024-08-01 14:39 UTC, beyhan approved these changes

2024-08-01 14:40 UTC, merged

2024-08-06 17:27 UTC, nader-ziada commented
@max-soe @beyhan The change to enable `use_dualstack_endpoint: true,` resulted in the integration and e2e tests failing

```
Bosh::AwsCloud::CloudV1 manual networking logging request_id when request_id is NOT present in the context does NOT log request_id
     Failure/Error: raise ArgumentError, "Invalid Configuration: Dualstack and custom endpoint are not supported"
     
     ArgumentError:
       Invalid Configuration: Dualstack and custom endpoint are not supported
```

This error comes from the aws sdk here: https://github.com/aws/aws-sdk-go-v2/blob/main/service/pinpoint/endpoints.go#L339 

maybe we can have a follow up PR to make this an optional configuration?

2024-08-07 07:51 UTC, beyhan commented
@nader-ziada thank you for the heads-up! We are looking into this and most probably it makes sense to make this optional configuration.

2024-08-07 12:17 UTC, max-soe commented
I created a new PR to fix this issue @beyhan @nader-ziada :
https://github.com/cloudfoundry/bosh-aws-cpi-release/pull/166

2024-08-07 12:29 UTC, ramonskie commented
Maby a good idea to document the regions that support this. Or point to aws documentation

2024-08-09 08:29 UTC, beyhan commented
We discussed this during the FI WG meeting yesterday and agreed to first get a better understanding of why the test failed and after that add documentation. FYI @a-hassanin, @jpalermo